## Датасет собран из базы данных переписи 1994 года и содержит данные о доходах.
### Информация о данных:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Проведите анализ данных при помощи Pandas выполнив поставленные задачи.
####

In [75]:
import pandas as pd
import numpy as np

In [3]:
# загружаем датасет
data = pd.read_csv("./data/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Посчитайте, сколько мужчин и женщин (признак *sex*) представлено в этом датасете**

In [113]:
data['sex'].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

**2. Каков средний возраст мужчин (признак *age*) по всему датасету?**

In [114]:
male_age_mean = data[data.sex=='Male']['age'].mean()
print(male_age_mean)

39.43354749885268

**3. Какова доля граждан Соединенных Штатов (признак *native-country*)?**

In [ ]:
usa_people_share = (data['native-country'] == 'United-States').mean()
usa_people_share

np.float64(0.895857006848684)

**4-5. Рассчитайте среднее значение и среднеквадратичное отклонение возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год**

In [20]:
data['salary'].unique()

<StringArray>
['<=50K', '>50K']
Length: 2, dtype: str

In [117]:
above_50k_mean = data[data['salary'] == '>50K']['age'].mean()
above_50k_std = data[data['salary'] == '>50K']['age'].std()

print(above_50k_mean, above_50k_std)

44.24984058155847 10.519027719851826

In [118]:
below_50k_mean = data[data['salary'] == '<=50K']['age'].mean()
below_50k_std = data[data['salary'] == '<=50K']['age'].std()

print(below_50k_mean, below_50k_std)

36.78373786407767 14.02008849082488

**6. Правда ли, что люди, которые получают больше 50k, имеют минимум высшее образование? (признак *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [121]:
higher_ed = ['Bachelors', 'Prof-school', 'Assoc-acdm', 'Assoc-voc', 'Masters', 'Doctorate']
result = data[data['salary'] == '>50K']['education'].isin(higher_ed).all()

print(f"Do all people earning >50K have higher education? {bool(result)}")

Do all people earning >50K have higher education? False

**7. Выведите статистику возраста для каждой расы (признак *race*) и каждого пола. Используйте *groupby* и *describe*. Найдите таким образом максимальный возраст мужчин расы *Asian-Pac-Islander*.**

In [122]:
result = data.groupby(by = ['race','sex'])['age'].describe()
asian_pac_islander_max_age = result.loc[('Asian-Pac-Islander', 'Male'), 'max']
asian_pac_islander_max_age

np.float64(90.0)

**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**

In [ ]:
married_men = data[
    (data['sex'] == 'Male') &
    (data['marital-status'].str.startswith('Married'))
]

high_salary_married_men = (married_men['salary'] == '>50K').mean()
high_salary_married_men

np.float64(0.4405139945351156)

In [ ]:
single_men = data[
    (data['sex'] == 'Male') &
    (~data['marital-status'].str.startswith('Married'))
]

high_salary_single_men = (single_men['salary'] == '>50K').mean()
high_salary_single_men

np.float64(0.08449509031397745)

In [ ]:
if high_salary_married_men > high_salary_single_men:
    print('The share is higher among married men.')
else:
    print('The share is higher among single men.')

The share is higher among married men.

**9. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много?**

In [ ]:
max_work_hours = data['hours-per-week'].max()

In [ ]:
max_work_hours_people = data[data['hours-per-week']==max_work_hours]
len(max_work_hours_people)

85

In [ ]:
max_work_hours_people_highsalary = (maxworkhours_people['salary']=='>50K').mean()
max_work_hours_people_highsalary*100

np.float64(29.411764705882355)

**10. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [ ]:
hrswk_country_salary_mean = data.groupby(by = ['native-country', 'salary'])['hours-per-week'].mean()
hrswk_country_salary_mean

native-country  salary
?               <=50K     40.164760
                >50K      45.547945
Cambodia        <=50K     41.416667
                >50K      40.000000
Canada          <=50K     37.914634
                            ...
United-States   >50K      45.505369
Vietnam         <=50K     37.193548
                >50K      39.200000
Yugoslavia      <=50K     41.600000
                >50K      49.500000
Name: hours-per-week, Length: 82, dtype: float64

**11.Сгруппируйте людей по возрастным группам *young*, *adult*, *retiree*, где:**
* *young* соответствует 16-35 лет
* *adult* - 35-70 лет
* *retiree* - 70-100 лет

**Проставьте название соответствуещей группы для каждого человека в новой колонке AgeGroup**

In [80]:
condlist = [((data['age'] >= 16) & (data['age'] < 35)), ((data['age'] >= 35) & (data['age'] < 70)), ((data['age'] >= 70) & (data['age'] < 100))]
choicelist = ['young', 'adult', 'retiree']
data['AgeGroup'] = np.select(condlist, choicelist, default='unknown')
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,AgeGroup
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,adult
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,adult
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,adult
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,adult
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,young

**12-13. Определите количество зарабатывающих >50K в каждой из возрастных групп (колонка AgeGroup), а также выведите название возрастной группы, в которой чаще зарабатывают больше 50К (>50K)**

In [ ]:
age_groups_high_salary = data[data['salary']=='>50K'].groupby(by=['AgeGroup'])['salary'].count()
age_groups_high_salary

AgeGroup
adult      6240
retiree     113
young      1488
Name: salary, dtype: int64

In [ ]:
print(age_groups_high_salary.idxmax())

adult

**14. Сгруппируйте людей по типу занятости (колонка occupation) и определите количество людей в каждой группе. После чего напишите функцию фильтрации filter_func, которая будет возвращать только те группы, в которых средний возраст (колонка age) не больше 40 и в которых все работники отрабатывают более 5 часов в неделю (колонка hours-per-week)**

In [102]:
occupations = data.groupby('occupation')
print(occupations.size())

occupation
?                    1843
Adm-clerical         3770
Armed-Forces            9
Craft-repair         4099
Exec-managerial      4066
Farming-fishing       994
Handlers-cleaners    1370
Machine-op-inspct    2002
Other-service        3295
Priv-house-serv       149
Prof-specialty       4140
Protective-serv       649
Sales                3650
Tech-support          928
Transport-moving     1597
dtype: int64

In [99]:
def filter_func(group):
    return (
        group['age'].mean() <= 40
        and
        (group['hours-per-week'] > 5).all()
    )

In [112]:
filtered = (occupations.filter(filter_func).groupby('occupation').size())
filtered

occupation
Armed-Forces    9
dtype: int64